<?php
declare(strict_types=1);

return [
    [
        'slug' => 'dashboard',
        'name' => 'Dashboard Executivo',
        'short_name' => 'Dashboard',
        'icon_class' => 'fa-solid fa-chart-line',
        'route_prefix' => '/dashboard',
        'description' => 'Painel macro da plataforma com visão consolidada de todos os módulos.',
        'is_available' => 0,
        'sort_order' => 1,
        'accent' => 'blue',
    ],
    [
        'slug' => 'propostas',
        'name' => 'Propostas',
        'short_name' => 'Propostas',
        'icon_class' => 'fa-solid fa-file-signature',
        'route_prefix' => '/propostas',
        'description' => 'Cadastro, acompanhamento, histórico e documentos das propostas.',
        'is_available' => 1,
        'sort_order' => 2,
        'accent' => 'red',
    ],
    [
        'slug' => 'busca',
        'name' => 'Busca',
        'short_name' => 'Busca',
        'icon_class' => 'fa-solid fa-magnifying-glass',
        'route_prefix' => '/busca',
        'description' => 'Pesquisa rápida em dados internos do sistema.',
        'is_available' => 1,
        'sort_order' => 3,
        'accent' => 'purple',
    ],
    [
        'slug' => 'cobrancas',
        'name' => 'Cobranças',
        'short_name' => 'Cobranças',
        'icon_class' => 'fa-solid fa-money-bill-wave',
        'route_prefix' => '/cobrancas',
        'description' => 'Régua de cobrança, acordos e recuperação de crédito.',
        'is_available' => 0,
        'sort_order' => 10,
        'accent' => 'green',
    ],
    [
        'slug' => 'demandas',
        'name' => 'Demandas',
        'short_name' => 'Demandas',
        'icon_class' => 'fa-solid fa-list-check',
        'route_prefix' => '/demandas',
        'description' => 'Controle de solicitações, providências e fluxos internos.',
        'is_available' => 0,
        'sort_order' => 11,
        'accent' => 'orange',
    ],
    [
        'slug' => 'processos',
        'name' => 'Processos',
        'short_name' => 'Processos',
        'icon_class' => 'fa-solid fa-scale-balanced',
        'route_prefix' => '/processos',
        'description' => 'Gestão processual e acompanhamento de fases e publicações.',
        'is_available' => 0,
        'sort_order' => 12,
        'accent' => 'slate',
    ],
    [
        'slug' => 'financeiro',
        'name' => 'Financeiro',
        'short_name' => 'Financeiro',
        'icon_class' => 'fa-solid fa-chart-pie',
        'route_prefix' => '/financeiro',
        'description' => 'Receitas, despesas, repasses e indicadores financeiros.',
        'is_available' => 0,
        'sort_order' => 13,
        'accent' => 'teal',
    ],
    [
        'slug' => 'clientes',
        'name' => 'Clientes',
        'short_name' => 'Clientes',
        'icon_class' => 'fa-solid fa-users',
        'route_prefix' => '/clientes',
        'description' => 'Base cadastral unificada de clientes avulsos, condomínios, unidades e contatos reaproveitáveis.',
        'is_available' => 1,
        'sort_order' => 14,
        'accent' => 'cyan',
    ],
    [
        'slug' => 'contratos',
        'name' => 'Contratos',
        'short_name' => 'Contratos',
        'icon_class' => 'fa-solid fa-file-contract',
        'route_prefix' => '/contratos',
        'description' => 'Modelos, vigências, assinaturas e gestão contratual.',
        'is_available' => 0,
        'sort_order' => 15,
        'accent' => 'indigo',
    ],
    [
        'slug' => 'config',
        'name' => 'Configurações',
        'short_name' => 'Config',
        'icon_class' => 'fa-solid fa-gear',
        'route_prefix' => '/config',
        'description' => 'Parâmetros, branding, usuários e módulos da plataforma.',
        'is_available' => 1,
        'sort_order' => 98,
        'accent' => 'dark',
        'superadmin_only' => 1,
    ],
    [
        'slug' => 'logs',
        'name' => 'Logs e Auditoria',
        'short_name' => 'Logs',
        'icon_class' => 'fa-solid fa-clock-rotate-left',
        'route_prefix' => '/logs',
        'description' => 'Rastreabilidade das ações críticas realizadas no sistema.',
        'is_available' => 1,
        'sort_order' => 99,
        'accent' => 'dark',
        'superadmin_only' => 1,
    ],
];
